import { Assessment, DomainScore, DomainDefinition } from '../types';

function ratingColor(rating: string): string {
  switch (rating) {
    case 'high': return '#ef4444';
    case 'medium': return '#f59e0b';
    case 'low': return '#22c55e';
    default: return '#94a3b8';
  }
}

function ratingLabel(rating: string): string {
  switch (rating) {
    case 'high': return 'HIGH';
    case 'medium': return 'MED';
    case 'low': return 'LOW';
    default: return rating?.toUpperCase() || 'N/A';
  }
}

export function generateHtmlReport(
  assessment: Assessment & { company_name: string; company_sector: string },
  domainScores: DomainScore[],
  domains: DomainDefinition[],
): string {
  // Parse domain summaries from the assessment
  let domainSummaries: Record<number, string> = {};
  if (assessment.domain_summaries) {
    try {
      domainSummaries = JSON.parse(assessment.domain_summaries as string);
    } catch (_e) { /* ignore parse errors */ }
  }

  const domainSections = domains.map(domain => {
    const domainRating = (assessment as any)[`domain${domain.number}_rating`];
    const summary = domainSummaries[domain.number] || '';

    return `
      <div style="margin-bottom: 10px;">
        <div style="display: flex; align-items: center; justify-content: space-between; border-bottom: 2px solid ${ratingColor(domainRating)}; padding-bottom: 2px; margin-bottom: 3px;">
          <span style="font-weight: 700; font-size: 11px; color: #1e293b;">D${domain.number}: ${domain.name}</span>
          <span style="font-size: 10px; font-weight: 700; color: ${ratingColor(domainRating)};">${ratingLabel(domainRating)}</span>
        </div>
        <p style="font-size: 10px; color: #374151; margin: 0; line-height: 1.35;">${summary || 'No summary available.'}</p>
      </div>
    `;
  }).join('');

  return `<!DOCTYPE html>
<html>
<head>
  <title>AI Risk Assessment - ${assessment.company_name}</title>
  <style>
    @page { size: letter; margin: 0.5in; }
    @media print {
      body { margin: 0; }
      .print-btn { display: none !important; }
    }
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      margin: 0.5in;
      color: #1e293b;
      line-height: 1.35;
      font-size: 10px;
    }
    .print-btn { position: fixed; top: 12px; right: 12px; padding: 6px 16px; background: #3b82f6; color: white; border: none; border-radius: 4px; cursor: pointer; font-size: 13px; }
  </style>
</head>
<body>
  <button class="print-btn" onclick="window.print()">Print / Save as PDF</button>

  <!-- Header -->
  <div style="border-bottom: 2px solid #1e293b; padding-bottom: 6px; margin-bottom: 8px;">
    <div style="display: flex; justify-content: space-between; align-items: baseline;">
      <div>
        <div style="font-size: 15px; font-weight: 700; color: #1e293b;">AI Disruption Risk Assessment</div>
        <div style="font-size: 13px; font-weight: 600; margin-top: 2px;">${assessment.company_name}</div>
      </div>
      <div style="text-align: right;">
        <span style="display: inline-block; padding: 3px 10px; border-radius: 4px; font-weight: 700; font-size: 13px; color: white; background: ${ratingColor(
          assessment.composite_score! <= 3.5 ? 'low' : assessment.composite_score! <= 6.5 ? 'medium' : 'high'
        )}">${assessment.composite_score}/10</span>
        <div style="font-size: 11px; font-weight: 600; margin-top: 2px;">${assessment.composite_rating}</div>
      </div>
    </div>
    <div style="font-size: 9px; color: #64748b; margin-top: 3px;">
      Sector: ${assessment.company_sector || 'N/A'} &nbsp;|&nbsp;
      Date: ${new Date(assessment.updated_at).toLocaleDateString()} &nbsp;|&nbsp;
      Model: ${assessment.ai_model || 'N/A'}
      ${assessment.user_modified ? ' &nbsp;|&nbsp; <em>User Modified</em>' : ''}
    </div>
  </div>

  <!-- Executive Summary -->
  ${assessment.narrative ? `
  <div style="margin-bottom: 10px;">
    <div style="font-size: 11px; font-weight: 700; color: #1e293b; margin-bottom: 3px;">Executive Summary</div>
    <div style="font-size: 10px; color: #374151; line-height: 1.35; background: #f8fafc; padding: 6px 8px; border-left: 3px solid #3b82f6; white-space: pre-wrap;">${assessment.narrative}</div>
  </div>` : ''}

  <!-- Domain Assessments -->
  ${domainSections}

  <!-- Notes -->
  ${assessment.notes ? `
  <div style="margin-top: 6px; padding: 5px 8px; background: #f8fafc; border-left: 3px solid #64748b; font-size: 10px;">
    <strong>Analyst Notes:</strong> ${assessment.notes}
  </div>` : ''}

  <div style="margin-top: 8px; padding-top: 4px; border-top: 1px solid #e2e8f0; color: #94a3b8; font-size: 8px;">
    Generated by Chuck &nbsp;|&nbsp; ${new Date().toISOString()}
  </div>
</body>
</html>`;
}
